<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-05-08 15:19:05.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

/**
 * Entity\Key
 *
 * @Entity()
 * @Table(name="`keys`", uniqueConstraints={@UniqueConstraint(name="id_UNIQUE", columns={"id"})})
 */
class Key
{
    /**
     * @Id
     * @Column(type="integer")
     * @GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Column(name="`key`", type="string", length=40, nullable=true)
     */
    protected $key;

    /**
     * @Column(name="`level`", type="integer")
     */
    protected $level;

    /**
     * @Column(type="boolean")
     */
    protected $ignore_limits;

    /**
     * @Column(type="integer", nullable=true)
     */
    protected $date_created;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Entity\Key
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of key.
     *
     * @param string $key
     * @return \Entity\Key
     */
    public function setKey($key)
    {
        $this->key = $key;

        return $this;
    }

    /**
     * Get the value of key.
     *
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Set the value of level.
     *
     * @param integer $level
     * @return \Entity\Key
     */
    public function setLevel($level)
    {
        $this->level = $level;

        return $this;
    }

    /**
     * Get the value of level.
     *
     * @return integer
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Set the value of ignore_limits.
     *
     * @param boolean $ignore_limits
     * @return \Entity\Key
     */
    public function setIgnoreLimits($ignore_limits)
    {
        $this->ignore_limits = $ignore_limits;

        return $this;
    }

    /**
     * Get the value of ignore_limits.
     *
     * @return boolean
     */
    public function getIgnoreLimits()
    {
        return $this->ignore_limits;
    }

    /**
     * Set the value of date_created.
     *
     * @param integer $date_created
     * @return \Entity\Key
     */
    public function setDateCreated($date_created)
    {
        $this->date_created = $date_created;

        return $this;
    }

    /**
     * Get the value of date_created.
     *
     * @return integer
     */
    public function getDateCreated()
    {
        return $this->date_created;
    }

    public function __sleep()
    {
        return array('id', 'key', 'level', 'ignore_limits', 'date_created');
    }
}