<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-05-12 12:05:26.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * Entity\Plan
 *
 * @Entity()
 * @Table(name="`plan`", uniqueConstraints={@UniqueConstraint(name="id_UNIQUE", columns={"id"})})
 */
class Plan
{
    /**
     * @Id
     * @Column(type="integer")
     * @GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Column(name="`name`", type="string", length=45, nullable=true)
     */
    protected $name;

    /**
     * @OneToMany(targetEntity="Workout", mappedBy="plan")
     * @JoinColumn(name="id", referencedColumnName="plan_id", nullable=false)
     */
    protected $workouts;

    public function __construct()
    {
        $this->workouts = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Entity\Plan
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of name.
     *
     * @param string $name
     * @return \Entity\Plan
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get the value of name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Add Workout entity to collection (one to many).
     *
     * @param \Entity\Workout $workout
     * @return \Entity\Plan
     */
    public function addWorkout(Workout $workout)
    {
        $this->workouts[] = $workout;

        return $this;
    }

    /**
     * Remove Workout entity from collection (one to many).
     *
     * @param \Entity\Workout $workout
     * @return \Entity\Plan
     */
    public function removeWorkout(Workout $workout)
    {
        $this->workouts->removeElement($workout);

        return $this;
    }

    /**
     * Get Workout entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getWorkouts()
    {
        return $this->workouts;
    }

    public function __sleep()
    {
        return array('id', 'name');
    }
}