<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-05-05 00:49:10.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

/**
 * Entity\Set
 *
 * @Entity()
 * @Table(name="`set`", indexes={@Index(name="fk_exercise_idx", columns={"exercise_id"})}, uniqueConstraints={@UniqueConstraint(name="id_UNIQUE", columns={"id"})})
 */
class Set
{
    /**
     * @Id
     * @Column(type="integer")
     * @GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Column(type="integer", nullable=true)
     */
    protected $rep_count;

    /**
     * @Column(type="smallint", nullable=true)
     */
    protected $dropset;

    /**
     * @Column(type="integer")
     */
    protected $schedule_workout_id;

    /**
     * @Column(type="integer")
     */
    protected $exercise_id;

    /**
     * @OneToOne(targetEntity="Exercise", inversedBy="set")
     * @JoinColumn(name="exercise_id", referencedColumnName="id", nullable=false)
     */
    protected $exercise;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Entity\Set
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of rep_count.
     *
     * @param integer $rep_count
     * @return \Entity\Set
     */
    public function setRepCount($rep_count)
    {
        $this->rep_count = $rep_count;

        return $this;
    }

    /**
     * Get the value of rep_count.
     *
     * @return integer
     */
    public function getRepCount()
    {
        return $this->rep_count;
    }

    /**
     * Set the value of dropset.
     *
     * @param integer $dropset
     * @return \Entity\Set
     */
    public function setDropset($dropset)
    {
        $this->dropset = $dropset;

        return $this;
    }

    /**
     * Get the value of dropset.
     *
     * @return integer
     */
    public function getDropset()
    {
        return $this->dropset;
    }

    /**
     * Set the value of schedule_workout_id.
     *
     * @param integer $schedule_workout_id
     * @return \Entity\Set
     */
    public function setScheduleWorkoutId($schedule_workout_id)
    {
        $this->schedule_workout_id = $schedule_workout_id;

        return $this;
    }

    /**
     * Get the value of schedule_workout_id.
     *
     * @return integer
     */
    public function getScheduleWorkoutId()
    {
        return $this->schedule_workout_id;
    }

    /**
     * Set the value of exercise_id.
     *
     * @param integer $exercise_id
     * @return \Entity\Set
     */
    public function setExerciseId($exercise_id)
    {
        $this->exercise_id = $exercise_id;

        return $this;
    }

    /**
     * Get the value of exercise_id.
     *
     * @return integer
     */
    public function getExerciseId()
    {
        return $this->exercise_id;
    }

    /**
     * Set Exercise entity (one to one).
     *
     * @param \Entity\Exercise $exercise
     * @return \Entity\Set
     */
    public function setExercise(Exercise $exercise)
    {
        $this->exercise = $exercise;

        return $this;
    }

    /**
     * Get Exercise entity (one to one).
     *
     * @return \Entity\Exercise
     */
    public function getExercise()
    {
        return $this->exercise;
    }

    public function __sleep()
    {
        return array('id', 'rep_count', 'dropset', 'schedule_workout_id', 'exercise_id');
    }
}