<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-05-08 15:19:05.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * Entity\User
 *
 * @Entity()
 * @Table(name="`user`", uniqueConstraints={@UniqueConstraint(name="id_UNIQUE", columns={"id"})})
 */
class User
{
    /**
     * @Id
     * @Column(type="integer")
     * @GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Column(type="string", length=45, nullable=true)
     */
    protected $first_name;

    /**
     * @Column(type="string", length=45, nullable=true)
     */
    protected $last_name;

    /**
     * @Column(type="string", length=45, nullable=true)
     */
    protected $nickname;

    /**
     * @OneToMany(targetEntity="WorkoutSchedule", mappedBy="user")
     * @JoinColumn(name="id", referencedColumnName="user_id", nullable=false)
     */
    protected $workoutSchedules;

    /**
     * @ManyToMany(targetEntity="Workout", mappedBy="users")
     */
    protected $workouts;

    public function __construct()
    {
        $this->workoutSchedules = new ArrayCollection();
        $this->workouts = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Entity\User
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of first_name.
     *
     * @param string $first_name
     * @return \Entity\User
     */
    public function setFirstName($first_name)
    {
        $this->first_name = $first_name;

        return $this;
    }

    /**
     * Get the value of first_name.
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->first_name;
    }

    /**
     * Set the value of last_name.
     *
     * @param string $last_name
     * @return \Entity\User
     */
    public function setLastName($last_name)
    {
        $this->last_name = $last_name;

        return $this;
    }

    /**
     * Get the value of last_name.
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * Set the value of nickname.
     *
     * @param string $nickname
     * @return \Entity\User
     */
    public function setNickname($nickname)
    {
        $this->nickname = $nickname;

        return $this;
    }

    /**
     * Get the value of nickname.
     *
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     * Add WorkoutSchedule entity to collection (one to many).
     *
     * @param \Entity\WorkoutSchedule $workoutSchedule
     * @return \Entity\User
     */
    public function addWorkoutSchedule(WorkoutSchedule $workoutSchedule)
    {
        $this->workoutSchedules[] = $workoutSchedule;

        return $this;
    }

    /**
     * Remove WorkoutSchedule entity from collection (one to many).
     *
     * @param \Entity\WorkoutSchedule $workoutSchedule
     * @return \Entity\User
     */
    public function removeWorkoutSchedule(WorkoutSchedule $workoutSchedule)
    {
        $this->workoutSchedules->removeElement($workoutSchedule);

        return $this;
    }

    /**
     * Get WorkoutSchedule entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getWorkoutSchedules()
    {
        return $this->workoutSchedules;
    }

    /**
     * Add Workout entity to collection.
     *
     * @param \Entity\Workout $workout
     * @return \Entity\User
     */
    public function addWorkout(Workout $workout)
    {
        $this->workouts[] = $workout;

        return $this;
    }

    /**
     * Remove Workout entity from collection.
     *
     * @param \Entity\Workout $workout
     * @return \Entity\User
     */
    public function removeWorkout(Workout $workout)
    {
        $this->workouts->removeElement($workout);

        return $this;
    }

    /**
     * Get Workout entity collection.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getWorkouts()
    {
        return $this->workouts;
    }

    public function __sleep()
    {
        return array('id', 'first_name', 'last_name', 'nickname');
    }
}