<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-05-12 12:05:26.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * Entity\Workout
 *
 * @Entity()
 * @Table(name="workout", indexes={@Index(name="fk_workout_plan1_idx", columns={"plan_id"})}, uniqueConstraints={@UniqueConstraint(name="id_UNIQUE", columns={"id"})})
 */
class Workout
{
    /**
     * @Id
     * @Column(type="integer")
     * @GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Column(name="`name`", type="string", length=45, nullable=true)
     */
    protected $name;

    /**
     * @Column(type="integer", nullable=true)
     */
    protected $plan_id;

    /**
     * @OneToMany(targetEntity="WorkoutSchedule", mappedBy="workout")
     * @JoinColumn(name="id", referencedColumnName="workout_id", nullable=false)
     */
    protected $workoutSchedules;

    /**
     * @ManyToOne(targetEntity="Plan", inversedBy="workouts")
     * @JoinColumn(name="plan_id", referencedColumnName="id")
     */
    protected $plan;

    /**
     * @ManyToMany(targetEntity="User", inversedBy="workouts")
     * @JoinTable(name="user_workout",
     *     joinColumns={@JoinColumn(name="workout_id", referencedColumnName="id", nullable=false)},
     *     inverseJoinColumns={@JoinColumn(name="user_id", referencedColumnName="id", nullable=false)}
     * )
     */
    protected $users;

    /**
     * @ManyToMany(targetEntity="Exercise", inversedBy="workouts")
     * @JoinTable(name="workout_exercise",
     *     joinColumns={@JoinColumn(name="workout_id", referencedColumnName="id", nullable=false)},
     *     inverseJoinColumns={@JoinColumn(name="exercise_id", referencedColumnName="id", nullable=false)}
     * )
     */
    protected $exercises;

    public function __construct()
    {
        $this->workoutSchedules = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->exercises = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Entity\Workout
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of name.
     *
     * @param string $name
     * @return \Entity\Workout
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get the value of name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set the value of plan_id.
     *
     * @param integer $plan_id
     * @return \Entity\Workout
     */
    public function setPlanId($plan_id)
    {
        $this->plan_id = $plan_id;

        return $this;
    }

    /**
     * Get the value of plan_id.
     *
     * @return integer
     */
    public function getPlanId()
    {
        return $this->plan_id;
    }

    /**
     * Add WorkoutSchedule entity to collection (one to many).
     *
     * @param \Entity\WorkoutSchedule $workoutSchedule
     * @return \Entity\Workout
     */
    public function addWorkoutSchedule(WorkoutSchedule $workoutSchedule)
    {
        $this->workoutSchedules[] = $workoutSchedule;

        return $this;
    }

    /**
     * Remove WorkoutSchedule entity from collection (one to many).
     *
     * @param \Entity\WorkoutSchedule $workoutSchedule
     * @return \Entity\Workout
     */
    public function removeWorkoutSchedule(WorkoutSchedule $workoutSchedule)
    {
        $this->workoutSchedules->removeElement($workoutSchedule);

        return $this;
    }

    /**
     * Get WorkoutSchedule entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getWorkoutSchedules()
    {
        return $this->workoutSchedules;
    }

    /**
     * Set Plan entity (many to one).
     *
     * @param \Entity\Plan $plan
     * @return \Entity\Workout
     */
    public function setPlan(Plan $plan = null)
    {
        $this->plan = $plan;

        return $this;
    }

    /**
     * Get Plan entity (many to one).
     *
     * @return \Entity\Plan
     */
    public function getPlan()
    {
        return $this->plan;
    }

    /**
     * Add User entity to collection.
     *
     * @param \Entity\User $user
     * @return \Entity\Workout
     */
    public function addUser(User $user)
    {
        $user->addWorkout($this);
        $this->users[] = $user;

        return $this;
    }

    /**
     * Remove User entity from collection.
     *
     * @param \Entity\User $user
     * @return \Entity\Workout
     */
    public function removeUser(User $user)
    {
        $user->removeWorkout($this);
        $this->users->removeElement($user);

        return $this;
    }

    /**
     * Get User entity collection.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * Add Exercise entity to collection.
     *
     * @param \Entity\Exercise $exercise
     * @return \Entity\Workout
     */
    public function addExercise(Exercise $exercise)
    {
        $exercise->addWorkout($this);
        $this->exercises[] = $exercise;

        return $this;
    }

    /**
     * Remove Exercise entity from collection.
     *
     * @param \Entity\Exercise $exercise
     * @return \Entity\Workout
     */
    public function removeExercise(Exercise $exercise)
    {
        $exercise->removeWorkout($this);
        $this->exercises->removeElement($exercise);

        return $this;
    }

    /**
     * Get Exercise entity collection.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getExercises()
    {
        return $this->exercises;
    }

    public function __sleep()
    {
        return array('id', 'name', 'plan_id');
    }
}