<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-05-12 12:05:26.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * Entity\WorkoutSchedule
 *
 * @Entity()
 * @Table(name="workout_schedule", indexes={@Index(name="fk_workout_schedule_workout1_idx", columns={"workout_id"}), @Index(name="fk_workout_schedule_user1_idx", columns={"user_id"})}, uniqueConstraints={@UniqueConstraint(name="id_UNIQUE", columns={"id"})})
 */
class WorkoutSchedule
{
    /**
     * @Id
     * @Column(type="integer")
     * @GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Column(name="`date`", type="date", nullable=true)
     */
    protected $date;

    /**
     * @Column(type="integer")
     */
    protected $workout_id;

    /**
     * @Column(type="integer")
     */
    protected $user_id;

    /**
     * @OneToMany(targetEntity="WorkoutScheduleExercise", mappedBy="workoutSchedule")
     * @JoinColumn(name="id", referencedColumnName="workout_schedule_id", nullable=false)
     */
    protected $workoutScheduleExercises;

    /**
     * @ManyToOne(targetEntity="Workout", inversedBy="workoutSchedules")
     * @JoinColumn(name="workout_id", referencedColumnName="id", nullable=false)
     */
    protected $workout;

    /**
     * @ManyToOne(targetEntity="User", inversedBy="workoutSchedules")
     * @JoinColumn(name="user_id", referencedColumnName="id", nullable=false)
     */
    protected $user;

    public function __construct()
    {
        $this->workoutScheduleExercises = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Entity\WorkoutSchedule
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of date.
     *
     * @param \DateTime $date
     * @return \Entity\WorkoutSchedule
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get the value of date.
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set the value of workout_id.
     *
     * @param integer $workout_id
     * @return \Entity\WorkoutSchedule
     */
    public function setWorkoutId($workout_id)
    {
        $this->workout_id = $workout_id;

        return $this;
    }

    /**
     * Get the value of workout_id.
     *
     * @return integer
     */
    public function getWorkoutId()
    {
        return $this->workout_id;
    }

    /**
     * Set the value of user_id.
     *
     * @param integer $user_id
     * @return \Entity\WorkoutSchedule
     */
    public function setUserId($user_id)
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * Get the value of user_id.
     *
     * @return integer
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Add WorkoutScheduleExercise entity to collection (one to many).
     *
     * @param \Entity\WorkoutScheduleExercise $workoutScheduleExercise
     * @return \Entity\WorkoutSchedule
     */
    public function addWorkoutScheduleExercise(WorkoutScheduleExercise $workoutScheduleExercise)
    {
        $this->workoutScheduleExercises[] = $workoutScheduleExercise;

        return $this;
    }

    /**
     * Remove WorkoutScheduleExercise entity from collection (one to many).
     *
     * @param \Entity\WorkoutScheduleExercise $workoutScheduleExercise
     * @return \Entity\WorkoutSchedule
     */
    public function removeWorkoutScheduleExercise(WorkoutScheduleExercise $workoutScheduleExercise)
    {
        $this->workoutScheduleExercises->removeElement($workoutScheduleExercise);

        return $this;
    }

    /**
     * Get WorkoutScheduleExercise entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getWorkoutScheduleExercises()
    {
        return $this->workoutScheduleExercises;
    }

    /**
     * Set Workout entity (many to one).
     *
     * @param \Entity\Workout $workout
     * @return \Entity\WorkoutSchedule
     */
    public function setWorkout(Workout $workout = null)
    {
        $this->workout = $workout;

        return $this;
    }

    /**
     * Get Workout entity (many to one).
     *
     * @return \Entity\Workout
     */
    public function getWorkout()
    {
        return $this->workout;
    }

    /**
     * Set User entity (many to one).
     *
     * @param \Entity\User $user
     * @return \Entity\WorkoutSchedule
     */
    public function setUser(User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get User entity (many to one).
     *
     * @return \Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    public function __sleep()
    {
        return array('id', 'date', 'workout_id', 'user_id');
    }
}