<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-05-05 00:49:10.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * Entity\WorkoutSchedule
 *
 * @Entity()
 * @Table(name="workout_schedule", indexes={@Index(name="fk_workout_schedule_user1_idx", columns={"user_id"})}, uniqueConstraints={@UniqueConstraint(name="id_UNIQUE", columns={"id"})})
 */
class WorkoutSchedule
{
    /**
     * @Id
     * @Column(type="integer")
     * @GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Column(name="`date`", type="date", nullable=true)
     */
    protected $date;

    /**
     * @Column(type="integer")
     */
    protected $user_id;

    /**
     * @ManyToOne(targetEntity="User", inversedBy="workoutSchedules")
     * @JoinColumn(name="user_id", referencedColumnName="id", nullable=false)
     */
    protected $user;

    /**
     * @ManyToMany(targetEntity="Workout", inversedBy="workoutSchedules")
     * @JoinTable(name="workout_has_workout_schedule",
     *     joinColumns={@JoinColumn(name="workout_schedule_id", referencedColumnName="id", nullable=false)},
     *     inverseJoinColumns={@JoinColumn(name="workout_id", referencedColumnName="id", nullable=false)}
     * )
     */
    protected $workouts;

    public function __construct()
    {
        $this->workouts = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Entity\WorkoutSchedule
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of date.
     *
     * @param \DateTime $date
     * @return \Entity\WorkoutSchedule
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get the value of date.
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set the value of user_id.
     *
     * @param integer $user_id
     * @return \Entity\WorkoutSchedule
     */
    public function setUserId($user_id)
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * Get the value of user_id.
     *
     * @return integer
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Set User entity (many to one).
     *
     * @param \Entity\User $user
     * @return \Entity\WorkoutSchedule
     */
    public function setUser(User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get User entity (many to one).
     *
     * @return \Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Add Workout entity to collection.
     *
     * @param \Entity\Workout $workout
     * @return \Entity\WorkoutSchedule
     */
    public function addWorkout(Workout $workout)
    {
        $workout->addWorkoutSchedule($this);
        $this->workouts[] = $workout;

        return $this;
    }

    /**
     * Remove Workout entity from collection.
     *
     * @param \Entity\Workout $workout
     * @return \Entity\WorkoutSchedule
     */
    public function removeWorkout(Workout $workout)
    {
        $workout->removeWorkoutSchedule($this);
        $this->workouts->removeElement($workout);

        return $this;
    }

    /**
     * Get Workout entity collection.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getWorkouts()
    {
        return $this->workouts;
    }

    public function __sleep()
    {
        return array('id', 'date', 'user_id');
    }
}