<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-05-05 00:47:56.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * Entity\WorkoutHasWorkoutSchedule
 *
 * @Entity()
 * @Table(name="workout_has_workout_schedule", indexes={@Index(name="fk_workout_has_workout_schedule_workout_schedule1_idx", columns={"workout_schedule_id", "workout_schedule_user_id"}), @Index(name="fk_workout_has_workout_schedule_workout1_idx", columns={"workout_id"})})
 */
class WorkoutHasWorkoutSchedule
{
    /**
     * @Id
     * @Column(type="integer")
     */
    protected $workout_id;

    /**
     * @Id
     * @Column(type="integer")
     */
    protected $workout_schedule_id;

    /**
     * @Id
     * @Column(type="integer")
     */
    protected $workout_schedule_user_id;

    /**
     * @OneToMany(targetEntity="Set", mappedBy="workoutHasWorkoutSchedule")
     * @JoinColumn(name="workout_id", referencedColumnName="schedule_workout_id", nullable=false)
     */
    protected $sets;

    /**
     * @ManyToOne(targetEntity="Workout", inversedBy="workoutHasWorkoutSchedules")
     * @JoinColumn(name="workout_id", referencedColumnName="id", nullable=false)
     */
    protected $workout;

    /**
     * @ManyToOne(targetEntity="WorkoutSchedule", inversedBy="workoutHasWorkoutSchedules")
     * @JoinColumns({@JoinColumn(name="workout_schedule_id", referencedColumnName="id", nullable=false),
     *     @JoinColumn(name="workout_schedule_user_id", referencedColumnName="id", nullable=false)
     * })
     */
    protected $workoutSchedule;

    public function __construct()
    {
        $this->sets = new ArrayCollection();
    }

    /**
     * Set the value of workout_id.
     *
     * @param integer $workout_id
     * @return \Entity\WorkoutHasWorkoutSchedule
     */
    public function setWorkoutId($workout_id)
    {
        $this->workout_id = $workout_id;

        return $this;
    }

    /**
     * Get the value of workout_id.
     *
     * @return integer
     */
    public function getWorkoutId()
    {
        return $this->workout_id;
    }

    /**
     * Set the value of workout_schedule_id.
     *
     * @param integer $workout_schedule_id
     * @return \Entity\WorkoutHasWorkoutSchedule
     */
    public function setWorkoutScheduleId($workout_schedule_id)
    {
        $this->workout_schedule_id = $workout_schedule_id;

        return $this;
    }

    /**
     * Get the value of workout_schedule_id.
     *
     * @return integer
     */
    public function getWorkoutScheduleId()
    {
        return $this->workout_schedule_id;
    }

    /**
     * Set the value of workout_schedule_user_id.
     *
     * @param integer $workout_schedule_user_id
     * @return \Entity\WorkoutHasWorkoutSchedule
     */
    public function setWorkoutScheduleUserId($workout_schedule_user_id)
    {
        $this->workout_schedule_user_id = $workout_schedule_user_id;

        return $this;
    }

    /**
     * Get the value of workout_schedule_user_id.
     *
     * @return integer
     */
    public function getWorkoutScheduleUserId()
    {
        return $this->workout_schedule_user_id;
    }

    /**
     * Add Set entity to collection (one to many).
     *
     * @param \Entity\Set $set
     * @return \Entity\WorkoutHasWorkoutSchedule
     */
    public function addSet(Set $set)
    {
        $this->sets[] = $set;

        return $this;
    }

    /**
     * Remove Set entity from collection (one to many).
     *
     * @param \Entity\Set $set
     * @return \Entity\WorkoutHasWorkoutSchedule
     */
    public function removeSet(Set $set)
    {
        $this->sets->removeElement($set);

        return $this;
    }

    /**
     * Get Set entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSets()
    {
        return $this->sets;
    }

    /**
     * Set Workout entity (many to one).
     *
     * @param \Entity\Workout $workout
     * @return \Entity\WorkoutHasWorkoutSchedule
     */
    public function setWorkout(Workout $workout = null)
    {
        $this->workout = $workout;

        return $this;
    }

    /**
     * Get Workout entity (many to one).
     *
     * @return \Entity\Workout
     */
    public function getWorkout()
    {
        return $this->workout;
    }

    /**
     * Set WorkoutSchedule entity (many to one).
     *
     * @param \Entity\WorkoutSchedule $workoutSchedule
     * @return \Entity\WorkoutHasWorkoutSchedule
     */
    public function setWorkoutSchedule(WorkoutSchedule $workoutSchedule = null)
    {
        $this->workoutSchedule = $workoutSchedule;

        return $this;
    }

    /**
     * Get WorkoutSchedule entity (many to one).
     *
     * @return \Entity\WorkoutSchedule
     */
    public function getWorkoutSchedule()
    {
        return $this->workoutSchedule;
    }

    public function __sleep()
    {
        return array('workout_id', 'workout_schedule_id', 'workout_schedule_user_id');
    }
}